const actionTypes = {
	STORE_DATA: "STORE_DATA",
	STORE_PROFILE: "STORE_PROFILE",
	STORE_BOOLEAN: "STORE_BOOLEAN",

	OPEN_OFFCANVAS: "OPEN_OFFCANVAS",
	CLOSE_OFFCANVAS: "CLOSE_OFFCANVAS",

	OPEN_UPDATEPROFILE: "OPEN_UPDATEPROFILE",
	CLOSE_UPDATEPROFILE: "CLOSE_UPDATEPROFILE",

	OPEN_PUSH_NOTIFICATION: "OPEN_PUSH_NOTIFICATION",
	CLOSE_PUSH_NOTIFICATION: "CLOSE_PUSH_NOTIFICATION",

	OPEN_NOTIFICATION: "OPEN_NOTIFICATION",
	OPEN_ERROR_MESSAGE: "OPEN_ERROR_MESSAGE",
	CLOSE_TOAST: "CLOSE_TOAST",

	OPEN_COMPLETE_PROFILE_CONFIRMATION: "OPEN_COMPLETE_PROFILE_CONFIRMATION",
	CLOSE_COMPLETE_PROFILE_CONFIRMATION: "CLOSE_COMPLETE_PROFILE_CONFIRMATION",

	OPEN_IMAGE_ZOOMER: "OPEN_IMAGE_ZOOMER",
	CLOSE_IMAGE_ZOOMER: "CLOSE_IMAGE_ZOOMER",

	OPEN_TAKE_ACTION_CONFIRMATION: "OPEN_TAKE_ACTION_CONFIRMATION",
	CLOSE_TAKE_ACTION_CONFIRMATION: "CLOSE_TAKE_ACTION_CONFIRMATION",
};

export default actionTypes;
